### ISSUE TITLE
Generates URLs with "(" while Javadoc has anchors with "-"

### ISSUE THREAD

**Issue by dadouf** [bluekeyes/sphinx-javalink#5]
Hey,

I've been using sphinx-javalink plugin for my project (http://dev.flitch.io). Good job, it's very neat and rather easy to setup ;)

I run into a problem that has to see with a difference of behaviour between what Javadoc expects, and what your tool generates. Example here: http://dev.flitch.io/sdkandroid.html#bind-to-flitchio

In that paragraph, the hyperlink over onCreate() is:
`http://dev.flitch.io/javadoc/com/supenta/flitchio/sdk/FlitchioController.html#onCreate()`

Yet when we follow the link, it doesn't go to the right anchor. Indeed, when we look for the anchor, it is actually:
`http://dev.flitch.io/javadoc/com/supenta/flitchio/sdk/FlitchioController.html#onCreate--`

The difference is with the last 2 characters, the brackets, that Javadoc has encoded as dashes. I couldn't see any configuration to influence this behaviour, in either Javadoc or sphinx-javalink. I use very standard settings in both.

What can I do?
Thank you very much.

**Comment by bluekeyes** [comment]
It looks like you're the first person to try this with Java 8 and the `javadoc` tool changed how it formats anchors in that release (see also [this IntelliJ IDEA bug](https://youtrack.jetbrains.com/issue/IDEA-118970)).

I'll look at adding an option to switch between Java 7 and Java 8 mode on a per-library basis, but I don't know when I'll have time to implement it. If you'd like to try fixing it, the relevant function is [here](https://github.com/bluekeyes/sphinx-javalink/blob/2370460d31444e3a5b89a867ebadc17f9f8f7c75/javalink/ref.py#L134). Locally, you could probably create a subclass of `JavarefRole`, override that method, then register your new role with Sphinx.

**Comment by dadouf** [comment]
Interesting, thanks for the insight! I'll look into it and submit a pull request if I make it.

**Comment by bluekeyes** [comment]
Fixed in 0.10.0 - https://pypi.python.org/pypi/sphinx-javalink/0.10.0
